### ISSUE TITLE
HDMI not working.

### ISSUE THREAD

**Issue by zhmpng** [danang-id/ASUS-TP412FA-ESP#1]
![Снимок экрана 2022-04-24 в 12 50 39](https://user-images.githubusercontent.com/75923630/164970691-97685b34-eeef-42ad-94e7-a22d8c9e813f.png)
Installed BigSur 11.6.5 along with OpenCore 7.6.
Among the detected malfunctions of the work: HDMI does not work, monitors report a lack of signal, and the PC lags for a couple of seconds when connected, but also does not see any monitors.
Please tell me if there is any solution for this?

Computer model -TP412FA-EC141T

**Comment by danang-id** [comment]
I'm sorry, but I will close this issue as I don't have this device with me anymore for a long time already.
